---
title: "Semester 1 Week 7"
editor: visual
---

## Bullet point intros and reducing perfectionism

In this session, we will go through everyone's bullet point intros. These are usually between half a page and a full page of A4, and don't need to be concrete.

We'll then look at reducing perfectionism and discuss this as a group.

### Expected progress

-   Around now, I would expect most ethics applications to be submitted (or in the final stages of draft) (especially if it's going through College rather than the intranet)
-   You should also have made a rough outline of your introduction and have done background reading
-   I will also ask you to pick a deadline for your Introduction, adding it to the shared deadlines spreadsheet

### Bullet point introductions

-   We will spend most of the session discussing bullet point introductions - please post these on Teams in advance and I will print off copies to make it easy to discuss.
    -   I will ask each person to talk about your project and what you currently think for your introduction in terms of structure
    -   I will then give some feedback on the suggested structure and the rest of the group can also ask questions etc.
    -   This is a good opportunity for the whole group to understand what everyone is doing for their project and if you can explain what you're doing to someone else at this point, it means that you have a plan.

### Reducing perfectionism

-   We will also talk about perfectionism and how it can be quite a big barrier in terms of not wanting to 'let go' of things
    -   Remember: a draft is just that: a draft. It's not the final version and doesn't need to be seen by anyone else.
    -   Breaking things into small chunks can help: you don't need to write a dissertation, you need to write the next paragraph/stence.
    -   Feedback will help make your work stronger in the end.

## External resources

Dr Carolina Kuepper-Tetzel found these resources on [Perfection Paralysis](https://hiddencurriculum.ca/wp-content/uploads/articulate_uploads/perfection-paralysis/index.html#/lessons/hAZjtzG_2XP4B6Quwveg8YvAI2zRrlqi) on the [Hidden Curriclum website](https://hiddencurriculum.ca/) (contains lots of useful resources)
