---
title: "Semester 1 Week 3"
editor: visual
---

## Ethics, research questions

In this session, we will talk about ethics and research questions. Depending on your project, you will either submit to secondary ethics, intranet ethics (low-risk option for Level 4 only) or College ethics (higher-risk/potential to publish for Level 4, all primary data collection for PGT)

### Expected progress and prep for the meeting

-   In Week 3, I would expect that you will be firming up your research questions and what yourdata collection/analysis will look like and have made progress in the proposal.
-   Please bring along the draft of your proposal and research questions so far.
-   Decide on a deadline for when you will submit your ethics application for feedback to me. Remember that you may need multiple drafts.
    -   Make a note of any questions or concerns you have about ethics at this stage ahead of the meeting.

## Internal resources

### Developing a research question

[Research Methods 1](https://bartlettje.github.io/RM1_Resources/intro-rationale.html#present-the-research-question-and-hypothesis) has some tips for students on how to construct Research Questions and hypotheses for quantitative research

[Research Methods 2](https://wtoivo.github.io/RM2-ODL-quali-book/qualitative-report.html?q=research%20ques#developing-a-research-question) has some tips for students on how to construct Research Questions for qualitative research

### Ethics

**Specific to School of Psychology & Neuroscience**: The Moodle (Level 4, PGT) has a folder with templates and exemplars for ethics that should be used
