---
title: "Semester 1 Week 9"
editor: visual
---

## Data and developing evaluation for the introduction

In this session, we will cover any data collection issues that you may have and also develop evaluation of the Introduction section.

### Expected progress

-   By now, ethics approvals should be imminent or through already
-   If you're doing primary data collection, you may have already started data collection, or might be getting materials together in anticipation of starting
-   If doing secondary data analysis, the timeline is a bit less pressured but by this point you should know exactly where your data is coming from and what you can do with it (caveats about unexpected hurdles not withstanding).
-   You should be actively working on your introductions.

### Data Collection (Quant survey projects)

-   If you are collecting primary data, for surveys and questionnaires I prefer Qualtrics. We have a UofG licence and there’s more information and the login via [UofG IT](https://www.gla.ac.uk/myglasgow/it/softwareandonlinetools/qualtrics/).
    -   Qualtrics is very powerful and doesn’t just do surveys, you can build experiments with randomised trials and between-subject conditions into it: [Building a psychology experiment](http://sites.cognitivescience.co/qualtrics/building-a-psychology-experiment) 
-   Test, test and test again
    -   It's important to make sure that scales are presented correctly. We've had one student have to start from scratch before because they put Strongly Agree - Disagree - neither agree nor disagree - Agree - Strongly Disagree and only noticed mid-way through data collection
    -   We also had one project where the participants saw a picture and it wasn't clear from the data which picture was presented (and it was the between subjects condition) and she had to start data collection again.
    -   Do not start data collection without extensive testing and I reiterate to let me know when it is ready for me to look over. Other supervisors may differ on this, but it's caused issues in the past (see examples above).
    -   You can[simulate responses in Qualtrics](https://www.qualtrics.com/support/survey-platform/survey-module/survey-tools/generating-test-responses/) which can help you test that your planned analyses are possible. You can also write the code for the final analysis before you data is collected which means when the time comes, all you need to do is run the code!
-   If you want to recruit Level 1 student you will need to provide an extended debrief and use Sona[ - see my sway](https://sway.cloud.microsoft/7OlDu5WmOmFjqDki?ref=Link&loc=play) on how to do this)

### Data Collection (Qual projects)

-   How are you planning on collecting data?
    -   If online, must use GDPR-approved system (e.g. Zoom or Teams)
    -   If in person, will need a) appropriate recording equipment, b) a quiet space
-   Some supervisors differ on their opinions on this, but I would encourage you to send out questions in advance for all participants, as it can be more accessible for certain people (e.g. those who are neurodivergent or who don't speak English as a first language)
-   Think about the process of collecting - it's entirely normal to be a bit nervous
    -   Practise setting things up/recording etc.
    -   It's good to pilot things (e.g. with a friend). I'm also happy to help in office hours etc. and you can also practise with each other (i.e. others in the group) to help get comfortable
    -   Can be helpful to write a list of everything you need to cover at the start and end so that they don't forget anything

### Data collection (secondary data)

By now you should have a concrete plan for your data collection / source.

-   If you're collecting Reddit data, you should have piloted downloading / searching for relevant URLs.

-   Inclusion, exclusion, and data saturation criteria are also really important - regardless of the data source, you might not want to use all of it and you may need to set a rule for when to stop collecting data (e.g., if you're using social media where there is essentially unlimited data). Make sure you have these criteria set in advance as much as possible.

-   At this point you also need to ensure that the data you have access to can actually be analysed in the way you've planned. With secondary data there's sometimes unforeseen difficulties you'll run into that you can't plan for, but taking the time to think things through as much as possible will save you time in the long-run.

-   If things do go wrong or change from the intended plan, don't worry - what's important is transparency about when and why decisions were made, not that you got everything right in advance

### Evaluation in introductions

In RM2, Wil and Ashley have made some excerpts from intros and discussions for their labs. In today's session, we will cover intros and do discussions in a later session.

We'll review the poor and stronger versions and we then have a discussion about it [(slides with notes)](https://gla-my.sharepoint.com/:p:/g/personal/ashley_robertson_glasgow_ac_uk/EXaejOFk4LhArFCk51SrtD8B8Y8Y05vjENf9k1Y7WfDPWA?e=yxNt5y). The three things we look at are: - Synthesising evidence - Focused criticism - Why is your study worth doing?

## Internal resources

Staff version of the lab slides on [Developing Evaluation in Introductions](https://gla-my.sharepoint.com/:p:/g/personal/ashley_robertson_glasgow_ac_uk/EXaejOFk4LhArFCk51SrtD8B8Y8Y05vjENf9k1Y7WfDPWA?e=yxNt5y) by Dr Wil Toivo and Dr. Ashley Roberston.

## External resources

[Guidance on SONA](https://gla-my.sharepoint.com/:b:/g/personal/ashley_robertson_glasgow_ac_uk/EaSibUgmSh1IpgvFOpf3kBoBH7fD4NiT29yNVP0fvblWYA?e=ZtuuEg)
