---
title: "Semester 2 Week 1"
editor: visual
---

## Receiving and applying feedback, presenting work

In this session, we see where everyone is now that we are back for Semester 2 (and the deadline will suddenly be just over two months away!). We will discuss receiving and applying feedback in this session, as well as presentation research.

### Expected progress

-   You should have submitted or be not too far off submitting a draft of the Introduction for feedback. You should also be working on you Methods.
-   If you're doing primary data, you should be recruiting participants by now.
-   If you're doing secondary data, you should have your final dataset and plan.

### Receiving and applying feedback

The main type of feedback that you will receive from me for any drafts will be:

-   In-text, and will either say what you did well, will say what could be improved or will ask a question.

-   I may point out one or two examples of things that could be improved throughout the draft – this does not mean that the ones I chose are the only examples. Try to look at the things I am saying and see if you can spot other examples. Often, this is to do with succinctness of writing, or overly using long/short paragraphs. I might give you an example of how you could cut out information you don't need, but it would be very repetitive to go through your whole draft with this level of detail.

-   If you are confused by one of my comments, think about why I might have made it, e.g. is it that you made a particular point, but it could be clearer? Did you cover it but somewhere else?

-   I will also give an overall summary comment I’ll provide the main things you do well and the main things I think it would be good to focus on. It's likely that I'll have covered these in more detail in the in-text comments

-   You might disagree with some of my feedback and that's okay! However, I encourage you to discuss it with me and I'll try to explain why I read it a particular way. You might then either decide to keep it as is or make some sort of change to make your intentions clearer.

### Presentations

-   I've noticed that quite a few students I supervise are nervous about presenting, so I talk to them about how they feel about it.
-   We discuss presenting their dissertation research, and I encourage them to take the opportunity to present when they get it. Although it can be anxiety provoking, it helps equip them with useful employability skills
-   I then highlight the Level 4 conference at the end of the semester, and the BPS conference that is usually at the end of March/beginning of April. I tell students that to support these, we will a) practice running through findings in the group (week 7) and we will b) book out a room to do a proper practice with slides (week 11). Both of these are no stakes and the purpose is to help students practice communicating their research in a safe environment.
-   We then discuss [some of my tips](https://gla-my.sharepoint.com/:w:/g/personal/ashley_robertson_glasgow_ac_uk/EQh-1I7HCsBGkpcK6WmxPUUB_7JmqoRw1LINLhLWATig6w?e=veACdI) for this (caveat: others may disagree) and together we plan out some concrete actions of what they could do to improve their experiences of presenting.

## Internal resources

[Guidance on presentations](https://gla-my.sharepoint.com/:w:/g/personal/ashley_robertson_glasgow_ac_uk/EQh-1I7HCsBGkpcK6WmxPUUB_7JmqoRw1LINLhLWATig6w?e=2AYZfm)

[Useful resources on feedback](https://moodle.gla.ac.uk/course/view.php?id=4529&section=5) in the Psychology & Neuroscience General Information moodle, including a [Feedback and Study Guide](https://moodle.gla.ac.uk/mod/book/view.php?id=1076576).

## Extenal resources

There are a few useful resources targeted at helping students get the most from feedback. We can't cover it all, so I tend to show students some parts of how to practically apply feedback in group supervision and we discuss it (e.g. SNOB analysis in the Salford document, Action Planning in the 'AdvanceHE Student Guide).

I always highlight that they are in fourth year and so will be used to applying feedback, but that it can be useful to consider how they might further improve things.

[Hepplestone et al., 2010](https://s3.eu-west-2.amazonaws.com/assets.creode.advancehe-document-manager/documents/hea/private/tfa_student_guide_1568036746.pdf)

[HEAdvance resource, August 2012](https://s3.eu-west-2.amazonaws.com/assets.creode.advancehe-document-manager/documents/hea/private/resources/10_feedback_resources_for_your_students2_1568036613.pdf)

[Salford Uni resource](https://www.salford.ac.uk/sites/default/files/2019-12/Making-the-Most-of-Feedback.pdf)

[Portsmouth Uni](https://www.port.ac.uk/student-life/help-and-advice/study-skills/speaking-skills-and-presentations) have some useful tips on presenting for students
